# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

KEYCHAIN_NAME = "larry-hybrid-app"
KEYCHAIN_PATH = "#{ENV["HOME"]}/Library/Keychains/#{KEYCHAIN_NAME}.keychain-db"
KEYCHAIN_PASSWORD = "larry4lyfe"

CURRENT_DIR = File.expand_path("../", File.dirname(__FILE__))

IOS_PROJECT_PATH = "#{CURRENT_DIR}/platforms/ios/{{appName}}.xcodeproj"

#Produced Build Assets
CORDOVA_DEBUG_APK_PATH = "#{CURRENT_DIR}/platforms/android/app/build/outputs/apk/debug/app-debug.apk"
CORDOVA_RELEASE_APK_PATH = "#{CURRENT_DIR}/platforms/android/app/build/outputs/apk/release/app-release.apk"
CORDOVA_DEBUG_IPA_PATH = "#{CURRENT_DIR}/platforms/ios/build/device/{{appName}}.ipa"
CORDOVA_RELEASE_IPA_PATH = "#{CURRENT_DIR}/platforms/ios/build/device/{{appName}}.ipa"
CORDOVA_XCARCHIVE_PATH = "#{CURRENT_DIR}/platforms/ios/{{appName}}.xcarchive"

RELEASE_DIR = "#{CURRENT_DIR}/_RELEASE_";

#Produced Release Assets
RELEASED_DEBUG_XCARCHIVE_PATH = "#{RELEASE_DIR}/{{appName}}-{{appVersion}}-debug.xcarchive"
RELEASED_XCARCHIVE_PATH = "#{RELEASE_DIR}/{{appName}}-{{appVersion}}.xcarchive"
RELEASED_DEBUG_APK_PATH = "#{RELEASE_DIR}/{{appName}}-{{appVersion}}-debug.apk"
RELEASED_APK_PATH = "#{RELEASE_DIR}/{{appName}}-{{appVersion}}.apk"
RELEASED_DEBUG_IPA_PATH = "#{RELEASE_DIR}/{{appName}}-{{appVersion}}-debug.ipa"
RELEASED_IPA_PATH = "#{RELEASE_DIR}/{{appName}}-{{appVersion}}.ipa"

UI.message "*** Project root is #{CURRENT_DIR}"

########################################################
#BUILD()
########################################################
lane :build do | options |
  if options[:targetPlatform] == 'ios'
    Fastlane::LaneManager.cruise_lane("ios", "build", options)
  elsif options[:targetPlatform] == 'android'
    Fastlane::LaneManager.cruise_lane("android", "build", options)
  #all case
  elsif [nil, 'all'].include?(options[:targetPlatform])
    Fastlane::LaneManager.cruise_lane("ios", "build", options)
    Fastlane::LaneManager.cruise_lane("android", "build", options)
  else
    UI.user_error!("(#{options[:targetPlatform]}) is an invalid targetPlatform, valid options are android, ios, all!")
  end
end
########################################################
#LAUNCH()
########################################################
lane :launch do | options |
  if options[:targetPlatform] == 'ios'
    Fastlane::LaneManager.cruise_lane("ios", "launch", options)
  elsif options[:targetPlatform] == 'android'
    Fastlane::LaneManager.cruise_lane("android", "launch", options)
  #all case
  elsif [nil, 'all'].include?(options[:targetPlatform])
    Fastlane::LaneManager.cruise_lane("ios", "launch", options)
    Fastlane::LaneManager.cruise_lane("android", "launch", options)
  else
    UI.user_error!("(#{options[:targetPlatform]}) is an invalid targetPlatform, valid options are android, ios, all!")
  end
end
########################################################
#RELEASE()
########################################################
lane :release do | options |
  if options[:targetPlatform] == 'ios'
    Fastlane::LaneManager.cruise_lane("ios", "release", options)
  elsif options[:targetPlatform] == 'android'
    Fastlane::LaneManager.cruise_lane("android", "release", options)
  #all case
  elsif [nil, 'all'].include?(options[:targetPlatform])
    Fastlane::LaneManager.cruise_lane("ios", "release", options)
    Fastlane::LaneManager.cruise_lane("android", "release", options)
  else
    UI.user_error!("(#{options[:targetPlatform]}) is an invalid targetPlatform, valid options are android, ios, all!")
  end
end
########################################################
#SUBMIT()
########################################################
lane :submit do | options |
  if options[:targetPlatform] == 'ios'
    Fastlane::LaneManager.cruise_lane("ios", "submit", options)
  elsif options[:targetPlatform] == 'android'
    Fastlane::LaneManager.cruise_lane("android", "submit", options)
  #all case
  elsif [nil, 'all'].include?(options[:targetPlatform])
    Fastlane::LaneManager.cruise_lane("ios", "submit", options)
    Fastlane::LaneManager.cruise_lane("android", "submit", options)
  else
    UI.user_error!("(#{options[:targetPlatform]}) is an invalid targetPlatform, valid options are android, ios, all!")
  end
end

########################################################
#START PLATFORM android
########################################################
platform :android do
  ##########
  #BUILD()
  ##########
  desc "Build the android application."
  lane :build do
    cordova(
      platform: 'android',
      release: false
    )
    if !File.file?(CORDOVA_DEBUG_APK_PATH)
      UI.build_failure!("Failed to build DEBUG APK!")
    else
      FileUtils.cp(CORDOVA_DEBUG_APK_PATH,RELEASED_DEBUG_APK_PATH)
    end
  end
  ##########
  #LAUNCH()
  ##########
  lane :launch do
    adb(
      command: "-d install -r \"#{RELEASED_DEBUG_APK_PATH}\""
    )
    adb(
      command: "shell am start -n {{appBundleId}}/.MainActivity"
    )
  end
  ##########
  #RELEASE()
  ##########
  lane :release do
    cordova(
      platform: 'android',
      release: true,
      keystore_path: "{{credentials.android.keystore}}", 
      keystore_alias: "{{credentials.android.alias}}", 
      keystore_password: "{{credentials.android.keystorePass}}", 
      key_password: "{{credentials.android.keyPass}}"
    )

    if !File.file?(CORDOVA_RELEASE_APK_PATH)
      UI.build_failure!("Failed to build APK!")
    else
      FileUtils.cp(CORDOVA_RELEASE_APK_PATH,RELEASED_APK_PATH)
    end

    UI.success "*** Signed APK released!!! (#{RELEASED_APK_PATH})"
  end
  ##########
  #SUBMIT()
  ##########
  lane :submit do
    supply(
      apk: RELEASED_APK_PATH
    )
  end
end
########################################################
#END PLATFORM android
#START PLATFORM ios
########################################################
platform :ios do
  #Private lane to unlock the keychain
  private_lane :setupKeychain do
    if !File.exists?(KEYCHAIN_PATH)
      create_keychain(
        password: KEYCHAIN_PASSWORD,
        path: KEYCHAIN_PATH,
        default_keychain: false,
        timeout: 3600,
        lock_when_sleeps: true
      )
    end
    
    unlock_keychain( 
      path: KEYCHAIN_PATH,
      password: KEYCHAIN_PASSWORD
    )
  end
  #install the provisioningProfile and return its uuid
  private_lane :setupProvisioningProfile do |options|
    UI.message "*** Setting up provisioningProfile (#{options[:provisioningProfile]})..."

    cmd = "grep UUID -A1 -a \"#{options[:provisioningProfile]}\" | grep -io \"[-A-F0-9]\\{36\\}\""
      
    #remove the trailing newline character
    provisioningProfileUuid = `#{cmd}`.strip

    dest = "#{ENV["HOME"]}/Library/MobileDevice/Provisioning Profiles/#{provisioningProfileUuid}.mobileprovision"
    if (dest != options[:provisioningProfile])
      UI.message "*** Installing provisioningProfile (#{provisioningProfileUuid})..."

      FileUtils.cp_r(options[:provisioningProfile],dest, :remove_destination => true, :preserve => false)
    end
    
    provisioningProfileUuid
  end
  ##########
  #BUILD()
  ##########
  desc "Build the ios application"
  lane :build do | options |
    if (options[:developmentProvisioningProfile])
      provisioningProfileUuid = setupProvisioningProfile(:provisioningProfile => options[:developmentProvisioningProfile])
    else
      setupKeychain()
      match(
        type: 'development',
        keychain_name: KEYCHAIN_NAME,
        keychain_password: KEYCHAIN_PASSWORD
      )
      provisioningProfileUuid = ENV['sigh_{{appBundleId}}_development']
    end
    cordova(
      platform: 'ios',
      provisioning_profile: provisioningProfileUuid,
      release: false,
      type: 'development'
    )

    if !File.file?(CORDOVA_DEBUG_IPA_PATH) && !File.file?(CORDOVA_XCARCHIVE_PATH)
      UI.build_failure!("Failed to build DEBUG IPA!")
    else
      FileUtils.cp_r(CORDOVA_XCARCHIVE_PATH,RELEASED_DEBUG_XCARCHIVE_PATH, :remove_destination => true)
      FileUtils.cp(CORDOVA_DEBUG_IPA_PATH,RELEASED_DEBUG_IPA_PATH)
    end
  end
  ##########
  #LAUNCH()
  ##########
  lane :launch do
    install_on_device(
      ipa: "#{CORDOVA_DEBUG_IPA_PATH}"
    )
  end
  ##########
  #RELEASE()
  ##########
  lane :release do | options |
    #if someone has specified signing info
    if (options[:appStoreProvisioningProfile])
        provisioningProfileUuid = setupProvisioningProfile(:provisioningProfile => options[:appStoreProvisioningProfile])
    else
      setupKeychain()
      match(
        type: 'appstore',
        keychain_name: KEYCHAIN_NAME,
        keychain_password: KEYCHAIN_PASSWORD
      )
      provisioningProfileUuid = ENV['sigh_{{appBundleId}}_development']
    end
    cordova(
      platform: 'ios',
      provisioning_profile: provisioningProfileUuid,
      release: true,
      type: 'appstore',
    )
    if !File.file?(CORDOVA_DEBUG_IPA_PATH) && !File.file?(CORDOVA_XCARCHIVE_PATH)
      UI.build_failure!("Failed to build IPA!")
    else
      FileUtils.cp_r(CORDOVA_XCARCHIVE_PATH,RELEASED_XCARCHIVE_PATH, :remove_destination => true)
      FileUtils.cp(CORDOVA_DEBUG_IPA_PATH,RELEASED_IPA_PATH)
    end
  end
  ##########
  #SUBMIT()
  ##########
  lane :submit do
    pilot(
      ipa: RELEASED_IPA_PATH
    )
  end
end
########################################################
#END PLATFORM ios
########################################################